// This file is generated by build/prebuild.
import Text from './Text'
import array_randomSwap from './array.random-swap'
import array_swap from './array.swap'
import common_getTypeName from './common.get-type-name'
import string_camelize from './string.camelize'
import string_hyphenate from './string.hyphenate'

const Allbox = {
  Text: Text,
  array: {
    randomSwap: array_randomSwap,
    swap: array_swap,
  },
  common: {
    getTypeName: common_getTypeName,
  },
  string: {
    camelize: string_camelize,
    hyphenate: string_hyphenate,
  },
}

export default Allbox
